version: '3'
services:
  discovery:
    image: ecirilog/discovery-service:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    networks:
      - eshop_nw
  config:
    image: ecirilog/config-server:0.0.1-SNAPSHOT
    environment:
      - EUREKA_HOST=discovery
      - EUREKA_PORT=8082
    ports:
      - "8888:8888"
    networks:
      - eshop_nw
  edge:
    image: ecirilog/edge-service:0.0.1-SNAPSHOT
    environment:
      - EUREKA_HOST=discovery
      - EUREKA_PORT=8082
    ports:
      - "8765"
    depends_on:
      - config
    networks:
      - eshop_nw
  catalog:
    image: ecirilog/catalog-service:0.0.1-SNAPSHOT
    environment:
      - CONFIG_BRANCH=docker
      - CONFIG_PROFILE=develop
      - EUREKA_HOST=discovery
      - EUREKA_PORT=8082
    ports:
      - "8080"
    depends_on:
      - config
    networks:
      - eshop_nw
  mongo-eshop:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - eshop_nw
networks:
  eshop_nw:
